"""`rules/RULES.md` generation (DESIGN §7.1: "generated from this registry
... so the human-readable catalog can never drift from the code"). STUB
this batch (CTO's batch-C red/green split call: "RULES.md generation ...
stay stubs -> red") — `_rules.py`'s registry is real and already carries
every rule's `id`/`why`, so the eventual implementation is a pure
string-render over `_rules.RULES`; it is not implemented THIS batch only
because `tk policy status --rules` (its CLI trigger) is itself gated behind
`policy.status()`, which is a stub.
"""

from __future__ import annotations

from pathlib import Path

from tradekit.policy._rules import RULES

# repo root, mirroring `_dials._REPO_ROOT_CONFIG`'s parents-count convention.
RULES_MD_PATH = Path(__file__).resolve().parents[3] / "rules" / "RULES.md"


def render_rules_md() -> str:
    """Render `_rules.RULES` into the Markdown catalog (ID / gate / dial /
    WHY, one row per rule, IDs in registry order). Pure — no filesystem
    access; `write_rules_md` is the I/O-performing caller."""
    last_id = RULES[-1].id if RULES else "R-000"
    lines = [
        "<!-- GENERATED by tradekit.policy._rules_md.write_rules_md — never hand-edit. -->",
        "<!-- Source of truth: src/tradekit/policy/_rules.py (DESIGN §7.1). -->",
        "",
        f"# Policy rules catalog (R-001..{last_id[-3:]})",
        "",
        "| ID | Applies to | WHY |",
        "| --- | --- | --- |",
    ]
    for rule in RULES:
        applies = ", ".join(sorted(rule.applies_to))
        why = rule.why.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {rule.id} | {applies} | {why} |")
    lines.extend(
        [
            "",
            "## Accepted-but-unenforced AccountConfig slots (TD-24)",
            "",
            "`AccountConfig.max_daily_profit` and `AccountConfig.consistency_rule` are "
            "ACCEPTED config slots — they validate and ledger on `AccountCreated` like every "
            "other `AccountConfig` field — but carry NO enforcing rule in P3 (Mike undecided, "
            "SPRINT P3 addendum). `None` disables them the same as every other TD-24 gate; a "
            "non-None value is accepted and stored but has no policy effect yet.",
            "",
        ]
    )
    return "\n".join(lines)


def write_rules_md() -> Path:
    """Write `render_rules_md()`'s output to `rules/RULES.md` (committed,
    generated, never hand-edited — DESIGN §7.1). Returns the path written."""
    RULES_MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    RULES_MD_PATH.write_text(render_rules_md(), encoding="utf-8")
    return RULES_MD_PATH


__all__ = ["RULES_MD_PATH", "render_rules_md", "write_rules_md"]
