"""Rules catalog v1 — R-001..R-018 (DESIGN §7.2; CTO addendum, story-3
pins). REAL this batch (declarative data the tests read, like `_dials.py` —
CTO's batch-C red/green split call): every `Rule.check` below is a PURE
function of `(action, ctx)`, unit-testable with a synthetic
`_context.PolicyContext` and no `_evaluate.py`/ledger involvement at all —
that pure core stays a stub this batch, but the rules it will eventually run
do not need it to be unit-tested individually.

IDs are stable forever (§7.2). `rules/RULES.md` (generated by
`tk policy status --rules`, batch-D+ CLI work) is produced FROM this
registry — one source of truth, never hand-edited.

Anti-permissive convention (CTO addendum): a rule whose needed context
field is `None` denies with `"insufficient_context"` folded into the
`RuleHit.measured` string (`"insufficient_context:<field>"`), NEVER a
silent pass. Fields that are legitimately empty in P2 (no open positions,
nothing graded yet) pass vacuously instead — see `tests/ASSUMPTIONS.md`'s
batch-C entry enumerating the split, rule by rule.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from decimal import Decimal

from tradekit.contracts import ProposedAction, RuleHit
from tradekit.policy._context import PolicyContext


@dataclass(frozen=True)
class Rule:
    id: str
    applies_to: frozenset[str]
    check: Callable[[ProposedAction, PolicyContext], RuleHit]
    why: str


def _hit(rule_id: str, *, allow: bool, measured: str | None, limit: str | None) -> RuleHit:
    return RuleHit(
        rule_id=rule_id,
        outcome="pass" if allow else "fail",
        measured=measured,
        limit=limit,
    )


def _insufficient(rule_id: str, field: str, limit: str | None = None) -> RuleHit:
    return _hit(rule_id, allow=False, measured=f"insufficient_context:{field}", limit=limit)


def _not_configured(rule_id: str, dial_field: str) -> RuleHit:
    """R-017/R-018 (TD-24, ASSUMPTIONS round-16): a `None` (disabled) dial
    is still CONSULTED — the rule emits a `RuleHit(outcome="not_configured")`
    so the audit trail shows it ran, distinct from both `pass` (a real check
    that allowed) and `fail`/`insufficient_context` (a real check that
    denied or lacked data). `evaluate_pure` treats `not_configured` the same
    as `pass` for the overall verdict (never denies on its own)."""
    return RuleHit(rule_id=rule_id, outcome="not_configured", measured=None, limit=dial_field)


def _order_notional(action: ProposedAction) -> Decimal | None:
    """qty * limit_price of the proposed order — `None` when the action
    carries no order, or a market order with no limit price to price it
    against (insufficient_context for any rule that needs a notional)."""
    order = action.order
    if order is None or order.limit_price is None:
        return None
    return order.qty * order.limit_price


def _is_live(action: ProposedAction) -> bool:
    return action.account_ref.startswith("live:")


def _is_paper(action: ProposedAction) -> bool:
    return action.account_ref.startswith("paper:")


def _is_advisory(action: ProposedAction) -> bool:
    return action.account_ref.startswith("advisory:")


# ---------------------------------------------------------------------------
# R-001 — kill switch
# ---------------------------------------------------------------------------


def _check_r001(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if ctx.halted:
        return _hit(
            "R-001", allow=False, measured="halted", limit=ctx.halt_reason or "unresolved"
        )
    return _hit("R-001", allow=True, measured="not_halted", limit=None)


# ---------------------------------------------------------------------------
# R-002 — promotion tier permits this account_ref + action
# ---------------------------------------------------------------------------

_MIN_TIER_RANK = {"T0": 0, "T1": 1, "T2": 2}


def _required_tier(action: ProposedAction) -> str:
    if _is_live(action):
        return "T2"
    if _is_paper(action):
        return "T1"
    return "T0"  # advisory/research


def _check_r002(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if ctx.account_tier is None:
        return _insufficient("R-002", "account_tier")
    required = _required_tier(action)
    ok = _MIN_TIER_RANK[ctx.account_tier] >= _MIN_TIER_RANK[required]
    return _hit("R-002", allow=ok, measured=ctx.account_tier, limit=required)


# ---------------------------------------------------------------------------
# R-003 — sufficient settled balance incl. fees
# ---------------------------------------------------------------------------


def _check_r003(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    notional = _order_notional(action)
    if notional is None:
        return _insufficient("R-003", "order_notional")
    if ctx.settled_balance_usd is None:
        return _insufficient("R-003", "settled_balance_usd")
    ok = ctx.settled_balance_usd >= notional
    return _hit("R-003", allow=ok, measured=str(notional), limit=str(ctx.settled_balance_usd))


# ---------------------------------------------------------------------------
# R-004 — per-asset allowlist (live only, SME §5)
# ---------------------------------------------------------------------------


def _check_r004(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if not _is_live(action):
        return _hit("R-004", allow=True, measured="not_live", limit=None)
    if action.order is None:
        return _insufficient("R-004", "order")
    symbol = action.order.asset.symbol
    ok = symbol in ctx.dials.allowed_assets_live
    return _hit(
        "R-004", allow=ok, measured=symbol, limit=",".join(ctx.dials.allowed_assets_live)
    )


# ---------------------------------------------------------------------------
# R-005 — max position notional (live: 5% of principal; paper: 10% equity)
# TD-24 migration (SPRINT P3 batch A, Mike-signed 2026-07-17): the live leg
# used to be a flat max_position_usd_live=$25 dial; it is now
# max_position_pct_live * ctx.account_principal_usd (5% * $500 default
# principal = $25, numerically unchanged for the default account). The
# paper leg is UNTOUCHED — still max_position_pct_paper * account_equity_usd.
# ---------------------------------------------------------------------------


def _check_r005(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    notional = _order_notional(action)
    if notional is None:
        return _insufficient("R-005", "order_notional")
    if _is_paper(action):
        if ctx.account_equity_usd is None:
            return _insufficient("R-005", "account_equity_usd")
        limit = ctx.dials.max_position_pct_paper * ctx.account_equity_usd
    else:
        if ctx.account_principal_usd is None:
            return _insufficient("R-005", "account_principal_usd")
        limit = ctx.dials.max_position_pct_live * ctx.account_principal_usd
    return _hit("R-005", allow=notional <= limit, measured=str(notional), limit=str(limit))


# ---------------------------------------------------------------------------
# R-006 — max total live exposure (D12), TD-24 migration: was a flat
# max_total_live_exposure_usd=$100 dial; now max_total_live_exposure_pct *
# ctx.account_principal_usd (20% * $500 = $100, unchanged for the default
# account).
# ---------------------------------------------------------------------------


def _check_r006(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    notional = _order_notional(action)
    if notional is None:
        return _insufficient("R-006", "order_notional")
    if ctx.account_principal_usd is None:
        return _insufficient("R-006", "account_principal_usd")
    projected = ctx.live_exposure_usd + notional
    limit = ctx.dials.max_total_live_exposure_pct * ctx.account_principal_usd
    return _hit("R-006", allow=projected <= limit, measured=str(projected), limit=str(limit))


# ---------------------------------------------------------------------------
# R-007 — daily trade count (live 3/day, paper 20/day)
# ---------------------------------------------------------------------------


def _check_r007(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if ctx.trades_today_count is None:
        return _insufficient("R-007", "trades_today_count")
    limit = (
        ctx.dials.max_daily_trades_live if _is_live(action) else ctx.dials.max_daily_trades_paper
    )
    ok = ctx.trades_today_count < limit
    return _hit("R-007", allow=ok, measured=str(ctx.trades_today_count), limit=str(limit))


# ---------------------------------------------------------------------------
# R-008 — min notional $10
# ---------------------------------------------------------------------------


def _check_r008(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    notional = _order_notional(action)
    if notional is None:
        return _insufficient("R-008", "order_notional")
    limit = ctx.dials.min_notional_usd
    return _hit("R-008", allow=notional >= limit, measured=str(notional), limit=str(limit))


# ---------------------------------------------------------------------------
# R-009 — drawdown circuit breaker (30d peak >= 10% -> no new positions)
# ---------------------------------------------------------------------------


def _check_r009(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if ctx.trailing_30d_drawdown_pct is None:
        return _insufficient("R-009", "trailing_30d_drawdown_pct")
    limit = ctx.dials.drawdown_breaker_pct
    ok = ctx.trailing_30d_drawdown_pct < limit
    return _hit(
        "R-009", allow=ok, measured=str(ctx.trailing_30d_drawdown_pct), limit=str(limit)
    )


# ---------------------------------------------------------------------------
# R-010 — thesis prerequisites: approved review + numeric EV + snapshot
# ---------------------------------------------------------------------------


def _check_r010(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if ctx.thesis_review_artifact_id is None:
        return _insufficient("R-010", "thesis_review_artifact_id")
    if ctx.thesis_market_snapshot_id is None:
        return _insufficient("R-010", "thesis_market_snapshot_id")
    if ctx.thesis_ev_ok is None:
        return _insufficient("R-010", "thesis_ev_ok")
    return _hit("R-010", allow=bool(ctx.thesis_ev_ok), measured=str(ctx.thesis_ev_ok), limit="True")


# ---------------------------------------------------------------------------
# R-011 — live sequence budget: T2 grants max 3 live trades
# ---------------------------------------------------------------------------


def _check_r011(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if not _is_live(action):
        return _hit("R-011", allow=True, measured="not_live", limit=None)
    if ctx.live_trades_remaining is None:
        return _insufficient("R-011", "live_trades_remaining")
    ok = ctx.live_trades_remaining > 0
    return _hit(
        "R-011",
        allow=ok,
        measured=str(ctx.live_trades_remaining),
        limit=str(ctx.dials.live_sequence_budget),
    )


# ---------------------------------------------------------------------------
# R-012 — sizing purity (F6): submitted size vs recorded SizingComputed
# ---------------------------------------------------------------------------


def _check_r012(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    notional = _order_notional(action)
    if notional is None:
        return _insufficient("R-012", "order_notional")
    if ctx.recorded_sizing_usd is None:
        return _insufficient("R-012", "recorded_sizing_usd")
    recorded = ctx.recorded_sizing_usd
    if recorded == 0:
        return _insufficient("R-012", "recorded_sizing_usd")
    deviation = abs(notional - recorded) / recorded
    limit = ctx.dials.sizing_tolerance_pct
    return _hit("R-012", allow=deviation <= limit, measured=str(deviation), limit=str(limit))


# ---------------------------------------------------------------------------
# R-013 — correlation cap: |r| > 0.75 to an open position
# ---------------------------------------------------------------------------


def _check_r013(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if not ctx.open_position_correlations:
        return _hit("R-013", allow=True, measured="no_open_positions", limit=None)
    worst_symbol, worst_corr = max(
        ctx.open_position_correlations.items(), key=lambda kv: abs(kv[1])
    )
    limit = ctx.dials.correlation_cap
    ok = abs(worst_corr) <= limit
    return _hit(
        "R-013", allow=ok, measured=f"{worst_symbol}:{worst_corr}", limit=str(limit)
    )


# ---------------------------------------------------------------------------
# R-014 — advisory cooling-off: manual trades over a FRACTION of principal
# need thesis age >= 24h. TD-24 migration: was a flat
# cooling_off_notional_usd=$200 dial; now cooling_off_pct *
# ctx.account_principal_usd (40% * $500 = $200, unchanged for the default
# account).
# ---------------------------------------------------------------------------


def _check_r014(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if not _is_advisory(action):
        return _hit("R-014", allow=True, measured="not_advisory", limit=None)
    notional = _order_notional(action)
    if notional is None:
        return _insufficient("R-014", "order_notional")
    if ctx.account_principal_usd is None:
        return _insufficient("R-014", "account_principal_usd")
    threshold = ctx.dials.cooling_off_pct * ctx.account_principal_usd
    if notional <= threshold:
        return _hit("R-014", allow=True, measured=str(notional), limit=None)
    if ctx.thesis_age_hours is None:
        return _insufficient("R-014", "thesis_age_hours")
    limit_hours = Decimal(ctx.dials.cooling_off_hours)
    ok = ctx.thesis_age_hours >= limit_hours
    return _hit("R-014", allow=ok, measured=str(ctx.thesis_age_hours), limit=str(limit_hours))


# ---------------------------------------------------------------------------
# R-015 — VOID-rate audit: >20% voids in trailing 20 graded
# ---------------------------------------------------------------------------


def _check_r015(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    outcomes = ctx.trailing_graded_outcomes
    if not outcomes:
        return _hit("R-015", allow=True, measured="no_graded_history", limit=None)
    void_rate = Decimal(sum(1 for o in outcomes if o == "VOID")) / Decimal(len(outcomes))
    limit = ctx.dials.void_rate_cap_pct
    ok = void_rate <= limit
    return _hit("R-015", allow=ok, measured=str(void_rate), limit=str(limit))


# ---------------------------------------------------------------------------
# R-016 — promotion metric gates (§9.4) — FLAGGED SEAM, see module docstring
# and PolicyContext.strategy_metrics: real mae.compute_strategy_metrics
# wiring is batch D's job; this rule reads a stubbed summary dict this batch.
# ---------------------------------------------------------------------------


def _check_r016(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    if ctx.strategy_metrics is None:
        return _insufficient("R-016", "strategy_metrics")
    passes = bool(ctx.strategy_metrics.get("passes_gates", False))
    return _hit("R-016", allow=passes, measured=str(passes), limit="True")


# ---------------------------------------------------------------------------
# R-017 — max_daily_drawdown (TD-24, SPRINT P3 batch A, Mike-signed
# 2026-07-17): disabled (dial resolves to None) -> not_configured, still
# ledgered for audit. Configured -> deny when today's realized-loss FRACTION
# of principal exceeds the dial; exactly at the dial ALLOWS (<=, not <).
# ---------------------------------------------------------------------------


def _check_r017(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    dial = ctx.account_max_daily_drawdown
    if dial is None:
        return _not_configured("R-017", "max_daily_drawdown")
    if ctx.daily_pnl_fraction is None:
        return _insufficient("R-017", "daily_pnl_fraction", limit=str(dial))
    loss_fraction = max(Decimal("0"), -ctx.daily_pnl_fraction)
    ok = loss_fraction <= dial
    return _hit("R-017", allow=ok, measured=str(loss_fraction), limit=str(dial))


# ---------------------------------------------------------------------------
# R-018 — max_lifetime_drawdown (TD-24): same shape as R-017, but against
# the account's lifetime peak-to-trough drawdown fraction of principal
# rather than today's realized pnl alone.
# ---------------------------------------------------------------------------


def _check_r018(action: ProposedAction, ctx: PolicyContext) -> RuleHit:
    dial = ctx.account_max_lifetime_drawdown
    if dial is None:
        return _not_configured("R-018", "max_lifetime_drawdown")
    if ctx.lifetime_drawdown_fraction is None:
        return _insufficient("R-018", "lifetime_drawdown_fraction", limit=str(dial))
    ok = ctx.lifetime_drawdown_fraction <= dial
    return _hit(
        "R-018", allow=ok, measured=str(ctx.lifetime_drawdown_fraction), limit=str(dial)
    )


_MUTATING = frozenset({"submit_order", "cancel", "promote", "void"})

RULES: tuple[Rule, ...] = (
    Rule(
        id="R-001",
        applies_to=_MUTATING,
        check=_check_r001,
        why=(
            "Kill switch: any unresolved HaltSet denies every mutating action. Manual "
            "circuit breaker for 'something is wrong, stop everything' — the fastest gate "
            "in the catalog because it must be. Dial: none."
        ),
    ),
    Rule(
        id="R-002",
        applies_to=frozenset({"submit_order"}),
        check=_check_r002,
        why=(
            "Promotion tier permits this account_ref + action (T0 research / T1 paper / "
            "T2 live) — an agent cannot trade live money it hasn't earned the right to "
            "touch yet (§7.3). Dial: none (tier state)."
        ),
    ),
    Rule(
        id="R-003",
        applies_to=frozenset({"submit_order"}),
        check=_check_r003,
        why=(
            "Sufficient settled balance incl. fees — an order the account cannot actually "
            "pay for is not a real trade, it's a lie the ledger would otherwise record. "
            "Dial: none (balance state)."
        ),
    ),
    Rule(
        id="R-004",
        applies_to=frozenset({"submit_order"}),
        check=_check_r004,
        why=(
            "Per-asset allowlist on live money: liquid large-caps + BTC/ETH only (SME §5) "
            "— an LLM agent does not get to discover illiquid microcaps with real dollars. "
            "Dial: allowed_assets_live."
        ),
    ),
    Rule(
        id="R-005",
        applies_to=frozenset({"submit_order"}),
        check=_check_r005,
        why=(
            "Max position notional: live 5% of account principal, paper 10% of equity. Caps "
            "single-position blast radius; a small bankroll survives being wrong, not being "
            "wrong big. Dial: max_position_pct_live / max_position_pct_paper (D12, TD-24)."
        ),
    ),
    Rule(
        id="R-006",
        applies_to=frozenset({"submit_order"}),
        check=_check_r006,
        why=(
            "Max total live exposure across all open live positions — a portfolio-level cap "
            "so no combination of individually-legal orders can compound into a bankroll-"
            "ending exposure. Dial: max_total_live_exposure_pct, fraction of account "
            "principal (D12, TD-24)."
        ),
    ),
    Rule(
        id="R-007",
        applies_to=frozenset({"submit_order"}),
        check=_check_r007,
        why=(
            "Daily trade count cap — deliberately tighter than 'unlimited' for anti-gaming "
            "reasons, cheap to dial up later. Dial: max_daily_trades_live / "
            "max_daily_trades_paper."
        ),
    ),
    Rule(
        id="R-008",
        applies_to=frozenset({"submit_order"}),
        check=_check_r008,
        why=(
            "Min notional $10 — blocks micro-trade series gaming and fee-noise grading "
            "(SME §5): ten $2 trades cannot manufacture a clean series. Dial: "
            "min_notional_usd."
        ),
    ),
    Rule(
        id="R-009",
        applies_to=frozenset({"submit_order"}),
        check=_check_r009,
        why=(
            "Drawdown circuit breaker: account drawdown >= 10% (30d peak) blocks new "
            "positions until a graded review — applies to advisory too (F7), because a "
            "losing streak is exactly when an agent should stop compounding it. Dial: "
            "drawdown_breaker_pct."
        ),
    ),
    Rule(
        id="R-010",
        applies_to=frozenset({"submit_order"}),
        check=_check_r010,
        why=(
            "Thesis prerequisites: approved review artifact + numeric EV block + market "
            "snapshot must all be present — a submission with no falsifiable, reviewed "
            "thesis behind it is not a trade the system can grade honestly. Dial: none."
        ),
    ),
    Rule(
        id="R-011",
        applies_to=frozenset({"submit_order"}),
        check=_check_r011,
        why=(
            "Live sequence budget: a T2 promotion grants exactly 3 live trades, then "
            "auto-reverts to review — live money is a probation, not a permanent unlock. "
            "Dial: live_sequence_budget."
        ),
    ),
    Rule(
        id="R-012",
        applies_to=frozenset({"submit_order"}),
        check=_check_r012,
        why=(
            "Sizing purity (F6): the submitted order size must match the recorded "
            "mae.size_position output for this thesis within tolerance — an agent cannot "
            "revenge-size past what its own sizing model computed. Dial: "
            "sizing_tolerance_pct."
        ),
    ),
    Rule(
        id="R-013",
        applies_to=frozenset({"submit_order"}),
        check=_check_r013,
        why=(
            "Correlation cap: a new position with |r| > 0.75 to an open position is not "
            "real diversification, it's the same bet twice — requires an explicit review "
            "flag before it can proceed. Dial: correlation_cap."
        ),
    ),
    Rule(
        id="R-014",
        applies_to=frozenset({"submit_order"}),
        check=_check_r014,
        why=(
            "Advisory cooling-off: manual trades over 40% of account principal need the "
            "backing thesis to be at least 24h old — a guardrail against same-day impulse "
            "trades dressed up as theses (F-guardrail 5). Dial: cooling_off_pct (fraction of "
            "principal, TD-24) / cooling_off_hours."
        ),
    ),
    Rule(
        id="R-015",
        applies_to=frozenset({"submit_order"}),
        check=_check_r015,
        why=(
            "VOID-rate audit: more than 20% voids in the trailing 20 graded theses blocks "
            "new submissions until a process review — voiding is for genuine structural "
            "invalidation, not a way to erase losers before they hurt a series. Dial: "
            "void_rate_window / void_rate_cap_pct (§10.4)."
        ),
    ),
    Rule(
        id="R-016",
        applies_to=frozenset({"promote"}),
        check=_check_r016,
        why=(
            "Promotion metric gates: the strategy acceptance table (§9.4) must pass at "
            "promotion evaluation — a good win rate on a coin flip is not evidence of edge. "
            "Dial: none (per-metric thresholds live in mae.compute_strategy_metrics; P2 "
            "reads a stubbed summary — batch D wires the real computation, FLAGGED SEAM)."
        ),
    ),
    Rule(
        id="R-017",
        applies_to=frozenset({"submit_order"}),
        check=_check_r017,
        why=(
            "Per-account max daily drawdown: today's realized loss must not exceed this "
            "FRACTION of account principal (TD-24) — enforced ONLY when the account's "
            "AccountConfig (or the config.toml default) sets it; an unconfigured account "
            "still gets a not_configured RuleHit so the audit trail shows the rule was "
            "consulted, never a silent skip. Dial: max_daily_drawdown (AccountConfig field) "
            "/ max_daily_drawdown_default (config.toml)."
        ),
    ),
    Rule(
        id="R-018",
        applies_to=frozenset({"submit_order"}),
        check=_check_r018,
        why=(
            "Per-account max lifetime drawdown: the account's peak-to-trough drawdown must "
            "not exceed this FRACTION of principal (TD-24) — same not_configured-when-"
            "disabled audit discipline as R-017. Dial: max_lifetime_drawdown (AccountConfig "
            "field) / max_lifetime_drawdown_default (config.toml)."
        ),
    ),
)

RULE_IDS: tuple[str, ...] = tuple(rule.id for rule in RULES)
RULES_BY_ID: dict[str, Rule] = {rule.id: rule for rule in RULES}


def applicable(action: ProposedAction) -> tuple[Rule, ...]:
    """Every rule whose `applies_to` includes `action.kind` — pure filter,
    no I/O; the order the pure core (`_evaluate.py`, stub this batch) would
    run them in."""
    return tuple(rule for rule in RULES if action.kind in rule.applies_to)


__all__ = ["RULES", "RULES_BY_ID", "RULE_IDS", "Rule", "applicable"]
